openapi: 3.0.3
info:
  title: EcoLedger - Auditoria Service API
  version: 1.0.0
  description: Serviço de validação e auditoria que consome movimentações e publica resultados.
servers:
  - url: https://api.ecoledger.local/auditoria
security:
  - bearerAuth: []
paths:
  /audits/{id}:
    get:
      summary: Recuperar registro de auditoria
      tags: [Audits]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Audit record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditRecord'
        '404':
          $ref: '#/components/responses/NotFound'
  /producers/{producerId}/audit-history:
    get:
      summary: Histórico de auditorias de um produtor
      tags: [Audits]
      parameters:
        - name: producerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Audit history
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/AuditRecord'
  /audits/{id}/review:
    post:
      summary: Registrar revisão manual por auditor
      tags: [Audits]
      security:
        - bearerAuth: [auditor:write]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [auditorId, result]
              properties:
                auditorId:
                  type: string
                result:
                  type: string
                  enum: [PASS, FAIL]
                observations:
                  type: string
      responses:
        '200':
          description: Review registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditRecord'
        '400':
          $ref: '#/components/responses/BadRequest'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    AuditRecord:
      type: object
      properties:
        id:
          type: string
        movementId:
          type: string
        producerId:
          type: string
        ruleVersion:
          type: string
        result:
          type: string
          enum: [PASS, FAIL, REQUIRES_MANUAL]
        evidence:
          type: array
          items:
            type: object
        processedAt:
          type: string
          format: date-time
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

