openapi: 3.0.3
info:
  title: EcoLedger - Serviço de Auditoria API
  version: 1.0.0
  description: Serviço de validação e auditoria que consome movimentações e publica resultados.
servers:
  - url: https://api.ecoledger.local/auditoria
security:
  - bearerAuth: [ ]
paths:
  /auditorias/{id}:
    get:
      summary: Recuperar registro de auditoria
      tags: [ Auditorias ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Registro de auditoria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistroAuditoria'
        '404':
          $ref: '#/components/responses/NotFound'
  /produtores/{producerId}/historico-auditorias:
    get:
      summary: Histórico de auditorias de um produtor
      tags: [ Auditorias ]
      parameters:
        - name: producerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Histórico de auditorias
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/RegistroAuditoria'
  /auditorias/{id}/revisao:
    post:
      summary: Registrar revisão manual por auditor
      tags: [ Auditorias ]
      security:
        - bearerAuth: [ auditor:write ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [ auditorId, resultado ]
              properties:
                auditorId:
                  type: string
                resultado:
                  type: string
                  enum: [ APROVADO, REPROVADO ]
                observacoes:
                  type: string
      responses:
        '200':
          description: Revisão registrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistroAuditoria'
        '400':
          $ref: '#/components/responses/BadRequest'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RegistroAuditoria:
      type: object
      properties:
        id:
          type: string
        movimentacaoId:
          type: string
        producerId:
          type: string
        versaoRegra:
          type: string
        resultado:
          type: string
          enum: [ APROVADO, REPROVADO, REQUER_REVISAO ]
        evidencias:
          type: array
          items:
            type: object
        processadoEm:
          type: string
          format: date-time
    Erro:
      type: object
      properties:
        codigo:
          type: string
        mensagem:
          type: string
  responses:
    BadRequest:
      description: Requisição inválida
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Erro'
    NotFound:
      description: Não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Erro'
