openapi: 3.0.3
info:
  title: EcoLedger - Serviço de Certificação API
  version: 1.0.0
  description: Serviço que calcula e expõe o estado do Selo Verde por produtor.
servers:
  - url: https://api.ecoledger.local/certificacao
security:
  - bearerAuth: []
paths:
  /selos/{producerId}:
    get:
      summary: Obter selo do produtor
      tags: [Selos]
      parameters:
        - name: producerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Selo verde
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SeloVerde'
        '404':
          $ref: '#/components/responses/NotFound'
  /selos/{producerId}/recalcular:
    post:
      summary: Forçar recálculo do selo
      tags: [Selos]
      security:
        - bearerAuth: [admin:selos]
      parameters:
        - name: producerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Recalculo iniciado
          content:
            application/json:
              schema:
                type: object
                properties:
                  novoStatus:
                    type: string
  /selos/{producerId}/historico:
    get:
      summary: Histórico de alterações do selo
      tags: [Selos]
      parameters:
        - name: producerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Histórico do selo
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/AlteracaoSelo'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SeloVerde:
      type: object
      properties:
        producerId:
          type: string
        status:
          type: string
          enum: [ATIVO, PENDENTE, INATIVO]
        nivel:
          type: string
          enum: [BRONZE, PRATA, OURO]
        pontuacao:
          type: number
        motivos:
          type: array
          items:
            type: string
        ultimoCheck:
          type: string
          format: date-time
    AlteracaoSelo:
      type: object
      properties:
        id:
          type: string
        producerId:
          type: string
        deStatus:
          type: string
        paraStatus:
          type: string
        motivo:
          type: string
        timestamp:
          type: string
          format: date-time
    Erro:
      type: object
      properties:
        codigo:
          type: string
        mensagem:
          type: string
  responses:
    NotFound:
      description: Não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Erro'
