openapi: 3.0.3
info:
  title: EcoLedger - Movimentacao Service API
  version: 1.0.0
  description: Serviço para registrar e consultar movimentações de commodities.
servers:
  - url: https://api.ecoledger.local/movements
security:
  - bearerAuth: []
paths:
  /movements:
    post:
      summary: Criar nova movimentação
      tags: [Movements]
      security:
        - bearerAuth: [producer:write]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovementCreate'
      responses:
        '201':
          description: Movement created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovementResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
  /movements/{id}:
    get:
      summary: Obter movimentação por id
      tags: [Movements]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Movement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movement'
        '404':
          $ref: '#/components/responses/NotFound'
  /producers/{producerId}/movements:
    get:
      summary: Listar movimentações de um produtor
      tags: [Movements]
      parameters:
        - name: producerId
          in: path
          required: true
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          schema:
            type: integer
            default: 20
        - name: fromDate
          in: query
          schema:
            type: string
            format: date
        - name: toDate
          in: query
          schema:
            type: string
            format: date
        - name: commodityId
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Paginated list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovementList'
  /commodities/{commodityId}/history:
    get:
      summary: Histórico por commodity
      tags: [Movements]
      parameters:
        - name: commodityId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Movement history
          content:
            application/json:
              schema:
                type: object
                properties:
                  movements:
                    type: array
                    items:
                      $ref: '#/components/schemas/Movement'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    MovementCreate:
      type: object
      required: [producerId, commodityId, type, quantity, unit, timestamp]
      properties:
        producerId:
          type: string
        commodityId:
          type: string
        type:
          type: string
          description: e.g., HARVEST, PROCESSING, TRANSPORT
        quantity:
          type: number
        unit:
          type: string
        timestamp:
          type: string
          format: date-time
        location:
          type: object
          properties:
            lat:
              type: number
            lon:
              type: number
        attachments:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              url:
                type: string
              hash:
                type: string
    MovementResponse:
      type: object
      properties:
        movementId:
          type: string
    Movement:
      type: object
      properties:
        id:
          type: string
        producerId:
          type: string
        commodityId:
          type: string
        type:
          type: string
        quantity:
          type: number
        unit:
          type: string
        timestamp:
          type: string
          format: date-time
        location:
          type: object
        attachments:
          type: array
          items:
            type: object
    MovementList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Movement'
        total:
          type: integer
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

