openapi: 3.0.3
info:
  title: EcoLedger - Serviço de Movimentação API
  version: 1.0.0
  description: Serviço para registrar e consultar movimentações de commodities.
servers:
  - url: https://api.ecoledger.local/movimentacoes
security:
  - bearerAuth: []
paths:
  /movimentacoes:
    post:
      summary: Criar nova movimentação
      tags: [Movimentacoes]
      security:
        - bearerAuth: [produtor:write]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovimentacaoCriacao'
      responses:
        '201':
          description: Movimentação criada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespostaMovimentacao'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
  /movimentacoes/{id}:
    get:
      summary: Obter movimentação por id
      tags: [Movimentacoes]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Movimentacao
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movimentacao'
        '404':
          $ref: '#/components/responses/NotFound'
  /produtores/{producerId}/movimentacoes:
    get:
      summary: Listar movimentações de um produtor
      tags: [Movimentacoes]
      parameters:
        - name: producerId
          in: path
          required: true
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          schema:
            type: integer
            default: 20
        - name: fromDate
          in: query
          schema:
            type: string
            format: date
        - name: toDate
          in: query
          schema:
            type: string
            format: date
        - name: commodityId
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Lista paginada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovimentacaoLista'
  /commodities/{commodityId}/historico:
    get:
      summary: Histórico por commodity
      tags: [Movimentacoes]
      parameters:
        - name: commodityId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Histórico de movimentações
          content:
            application/json:
              schema:
                type: object
                properties:
                  movimentacoes:
                    type: array
                    items:
                      $ref: '#/components/schemas/Movimentacao'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    MovimentacaoCriacao:
      type: object
      required: [producerId, commodityId, tipo, quantidade, unidade, timestamp]
      properties:
        producerId:
          type: string
        commodityId:
          type: string
        tipo:
          type: string
          description: 'ex: COLHEITA, PROCESSAMENTO, TRANSPORTE'
        quantidade:
          type: number
        unidade:
          type: string
        timestamp:
          type: string
          format: date-time
        localizacao:
          type: object
          properties:
            lat:
              type: number
            lon:
              type: number
        anexos:
          type: array
          items:
            type: object
            properties:
              tipo:
                type: string
              url:
                type: string
              hash:
                type: string
    RespostaMovimentacao:
      type: object
      properties:
        movimentacaoId:
          type: string
    Movimentacao:
      type: object
      properties:
        id:
          type: string
        producerId:
          type: string
        commodityId:
          type: string
        tipo:
          type: string
        quantidade:
          type: number
        unidade:
          type: string
        timestamp:
          type: string
          format: date-time
        localizacao:
          type: object
        anexos:
          type: array
          items:
            type: object
    MovimentacaoLista:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Movimentacao'
        total:
          type: integer
    Erro:
      type: object
      properties:
        codigo:
          type: string
        mensagem:
          type: string
  responses:
    BadRequest:
      description: Requisição inválida
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Erro'
    Forbidden:
      description: Proibido
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Erro'
    NotFound:
      description: Não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Erro'
