openapi: 3.0.3
info:
  title: EcoLedger - Serviço de Notificação API
  version: 1.0.0
  description: Serviço central de notificações (email, push, webhook) e gerenciamento de preferências.
servers:
  - url: https://api.ecoledger.local/notificacoes
security:
  - bearerAuth: []
paths:
  /notificacoes/enviar:
    post:
      summary: Enviar notificação
      tags: [Notificacoes]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnviarNotificacao'
      responses:
        '202':
          description: Aceito
          content:
            application/json:
              schema:
                type: object
                properties:
                  notificacaoId:
                    type: string
  /preferencias/{userId}:
    get:
      summary: Obter preferências de notificação do usuário
      tags: [Preferencias]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Preferências
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Preferencias'
    patch:
      summary: Atualizar preferências de notificação
      tags: [Preferencias]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Preferencias'
      responses:
        '200':
          description: Atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Preferencias'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    EnviarNotificacao:
      type: object
      required: [templateId, data]
      properties:
        paraUsuarioId:
          type: string
        canal:
          type: string
          enum: [email, push, webhook]
        templateId:
          type: string
        data:
          type: object
    Preferencias:
      type: object
      properties:
        userId:
          type: string
        canais:
          type: object
          properties:
            email:
              type: boolean
            push:
              type: boolean
            webhook:
              type: boolean
  schemas:
    Erro:
      type: object
      properties:
        codigo:
          type: string
        mensagem:
          type: string
