openapi: 3.0.3
info:
  title: EcoLedger - Serviço de Usuários API
  version: 1.0.0
  description: API para registro, autenticação e gestão de usuários (Produtores, Analistas, Auditores).
servers:
  - url: https://api.ecoledger.local/usuarios
security:
  - bearerAuth: []
paths:
  /cadastros:
    post:
      summary: Submete novo cadastro de usuário
      tags:
        - Cadastros
      parameters:
        - name: Idempotency-Key
          in: header
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CadastroCriacao'
      responses:
        '201':
          description: Cadastro criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespostaCadastro'
        '400':
          $ref: '#/components/responses/BadRequest'
  /cadastros/{id}:
    get:
      summary: Recupera pedido de cadastro
      tags:
        - Cadastros
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cadastro recuperado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cadastro'
        '404':
          $ref: '#/components/responses/NotFound'
  /auth/login:
    post:
      summary: Autenticar usuário (email + senha)
      tags:
        - Autenticacao
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenAuth'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /usuarios/{id}:
    get:
      summary: Obter perfil do usuário
      tags:
        - Usuarios
      security:
        - bearerAuth: [usuarios:read]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Perfil do usuário
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      summary: Atualizar perfil do usuário (parcial)
      tags:
        - Usuarios
      security:
        - bearerAuth: [usuarios:write]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioAtualizacao'
      responses:
        '200':
          description: Usuário atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
  /usuarios/{id}/status:
    patch:
      summary: Atualiza status do usuário (admin/analista)
      tags:
        - Usuarios
      security:
        - bearerAuth: [admin:usuarios]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [status]
              properties:
                status:
                  type: string
                  enum: [PENDENTE, APROVADO, REJEITADO]
                reason:
                  type: string
      responses:
        '200':
          description: Status atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: string
        nome:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
          enum: [produtor, analista, auditor]
        documento:
          type: string
        status:
          type: string
          enum: [PENDENTE, APROVADO, REJEITADO]
        criadoEm:
          type: string
          format: date-time
      required: [id, nome, email, role, status, criadoEm]
    CadastroCriacao:
      type: object
      required: [nome, email, documento, role]
      properties:
        nome:
          type: string
        email:
          type: string
          format: email
        documento:
          type: string
        role:
          type: string
          enum: [produtor, analista, auditor]
        dadosFazenda:
          type: object
          additionalProperties: true
        anexos:
          type: array
          items:
            type: object
            properties:
              tipo:
                type: string
              url:
                type: string
    RespostaCadastro:
      type: object
      properties:
        cadastroId:
          type: string
        status:
          type: string
    Cadastro:
      allOf:
        - $ref: '#/components/schemas/RespostaCadastro'
        - type: object
          properties:
            candidatoUsuario:
              $ref: '#/components/schemas/Usuario'
            submetidoEm:
              type: string
              format: date-time
    TokenAuth:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        expiresIn:
          type: integer
    UsuarioAtualizacao:
      type: object
      properties:
        nome:
          type: string
        dadosFazenda:
          type: object
          additionalProperties: true
    Erro:
      type: object
      properties:
        codigo:
          type: string
        mensagem:
          type: string
  responses:
    BadRequest:
      description: Requisição inválida
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Erro'
    Unauthorized:
      description: Não autorizado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Erro'
    Forbidden:
      description: Proibido
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Erro'
    NotFound:
      description: Não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Erro'
