openapi: 3.0.3
info:
  title: EcoLedger - Users Service API
  version: 1.0.0
  description: API para registro, autenticação e gestão de usuários (Produtores, Analistas, Auditores).
servers:
  - url: https://api.ecoledger.local/users
security:
  - bearerAuth: []
paths:
  /registrations:
    post:
      summary: Submete novo cadastro de usuário
      tags:
        - Registrations
      parameters:
        - name: Idempotency-Key
          in: header
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationCreate'
      responses:
        '201':
          description: Registration created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
  /registrations/{id}:
    get:
      summary: Recupera pedido de cadastro
      tags:
        - Registrations
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Registration retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Registration'
        '404':
          $ref: '#/components/responses/NotFound'
  /auth/login:
    post:
      summary: Autenticar usuário (email + senha)
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /users/{id}:
    get:
      summary: Obter perfil do usuário
      tags:
        - Users
      security:
        - bearerAuth: [users:read]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      summary: Atualizar perfil do usuário (parcial)
      tags:
        - Users
      security:
        - bearerAuth: [users:write]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
  /users/{id}/status:
    patch:
      summary: Atualiza status do usuário (admin/analista)
      tags:
        - Users
      security:
        - bearerAuth: [admin:users]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [status]
              properties:
                status:
                  type: string
                  enum: [PENDING, APPROVED, REJECTED]
                reason:
                  type: string
      responses:
        '200':
          description: Status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
          enum: [producer, analyst, auditor]
        documentId:
          type: string
        status:
          type: string
          enum: [PENDING, APPROVED, REJECTED]
        createdAt:
          type: string
          format: date-time
      required: [id, name, email, role, status, createdAt]
    RegistrationCreate:
      type: object
      required: [name, email, documentId, role]
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        documentId:
          type: string
        role:
          type: string
          enum: [producer, analyst, auditor]
        farmData:
          type: object
          additionalProperties: true
        attachments:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              url:
                type: string
    RegistrationResponse:
      type: object
      properties:
        registrationId:
          type: string
        status:
          type: string
    Registration:
      allOf:
        - $ref: '#/components/schemas/RegistrationResponse'
        - type: object
          properties:
            userCandidate:
              $ref: '#/components/schemas/User'
            submittedAt:
              type: string
              format: date-time
    AuthToken:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        expiresIn:
          type: integer
    UserUpdate:
      type: object
      properties:
        name:
          type: string
        farmData:
          type: object
          additionalProperties: true
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
